# Generated by Django 3.1.1 on 2020-09-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='data_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='data_ini',
            new_name='date_ini',
        ),
    ]
